using Microsoft.AspNetCore.Identity;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Serilog;
using System.Security.Claims;
using todostodo.api.Data;
using todostodo.api.Middleware;
using todostodo.api.Models;

var builder = WebApplication.CreateBuilder(args);

// using Serilog for logging, structured  and integrates cleanly with ILogger
// better than defaul logger for scalling, has cloud sink capabilities with datadog, properties become searchable
builder.Host.UseSerilog((ctx, config) =>
    config
        .ReadFrom.Configuration(ctx.Configuration)
        .Enrich.FromLogContext()
        .WriteTo.Console());

// :memory: is what makes it in-memory
var connection = new SqliteConnection("Data Source=:memory:");

connection.Open();

// add db context with the in-memory connection
builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseSqlite(connection)
);

// adds Identity services to the dependency injection container
builder.Services.AddAuthorization();

// activate API endpoints for Identity
// by default cookies and proprietary tokens are activated >> issuesd at login if the useCookies query string param is true
// this calls what would be AddAuthentication() on a non-Identity API
builder.Services.AddIdentityApiEndpoints<User>().AddEntityFrameworkStores<AppDbContext>();

// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
// replacement for swagger
builder.Services.AddOpenApi();

builder.Services.AddControllers();

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddValidation();

builder.Services.AddProblemDetails();
builder.Services.AddExceptionHandler<GlobalExceptionHandler>();

builder.Services.AddCors(options =>
{
    options.AddPolicy(name: "todostodo.web", policy =>
    {
        policy.WithOrigins("http://localhost:5173").AllowAnyHeader().AllowAnyMethod();
    });
});

var app = builder.Build();

// map identity api endpoints
app.MapIdentityApi<User>();

// Explicit logout — MapIdentityApi doesn't expose this in .NET 10
app.MapPost("/logout", async (SignInManager<User> signInManager) =>
{
    await signInManager.SignOutAsync();
    return Results.Ok();
}).RequireAuthorization();

if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
}

using (var scope = app.Services.CreateScope())
{
    var dbContext = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    dbContext.Database.EnsureCreated();
}

// UseExceptionHandler must be first so it wraps all subsequent middleware exceptions.
app.UseExceptionHandler();

app.UseAuthentication();
app.UseAuthorization();

app.UseSwagger();
app.UseSwaggerUI();

app.UseSerilogRequestLogging(options =>
{
    options.EnrichDiagnosticContext = (diag, ctx) =>
    {
        var userId = ctx.User.FindFirstValue(ClaimTypes.NameIdentifier);
        if (userId is not null)
            diag.Set("UserId", userId);
    };
});

app.UseCors("todostodo.web");

app.MapControllers();

app.Run();

/// <summary>
/// Exposes the implicit Program class generated by top-level statements so that
/// <c>WebApplicationFactory&lt;Program&gt;</c> can reference it from the integration test project.
/// </summary>
public partial class Program { }