using Microsoft.AspNetCore.Identity;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using todostodo.api.Data;
using todostodo.api.Middleware;
using todostodo.api.Models;

var builder = WebApplication.CreateBuilder(args);

// :memory: is what makes it in-memory
var connection = new SqliteConnection("Data Source=:memory:");

connection.Open();

// add db context with the in-memory connection
builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseSqlite(connection)
);

// adds Identity services to the dependency injection container
builder.Services.AddAuthorization();

// activate API endpoints for Identity
// by default cookies and proprietary tokens are activated >> issuesd at login if the useCookies query string param is true
// this calls what would be AddAuthentication() on a non-Identity API
builder.Services.AddIdentityApiEndpoints<User>().AddEntityFrameworkStores<AppDbContext>();

// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
// replacement for swagger
builder.Services.AddOpenApi();

builder.Services.AddControllers();

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddValidation();

builder.Services.AddProblemDetails();
builder.Services.AddExceptionHandler<GlobalExceptionHandler>();

builder.Services.AddCors(options =>
{
    options.AddPolicy(name: "todostodo.web", policy =>
    {
        policy.WithOrigins("http://localhost:5173").AllowAnyHeader().AllowAnyMethod();
    });
}); 

var app = builder.Build();

// map identity api endpoints
app.MapIdentityApi<User>();

// Explicit logout — MapIdentityApi doesn't expose this in .NET 10
app.MapPost("/logout", async (SignInManager<User> signInManager) =>
{
    await signInManager.SignOutAsync();
    return Results.Ok();
}).RequireAuthorization();

if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
}

// TODO secure endpoints - in controller [Authorize] attribute

using (var scope = app.Services.CreateScope())
{
    var dbContext = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    dbContext.Database.EnsureCreated();
}

app.UseExceptionHandler();

app.UseAuthentication();
app.UseAuthorization();

// only in dev >> remove for openapi?
app.UseSwagger();
app.UseSwaggerUI();

app.UseCors("todostodo.web");

app.MapControllers();

app.Run();

/// <summary>
/// Exposes the implicit Program class generated by top-level statements so that
/// <c>WebApplicationFactory&lt;Program&gt;</c> can reference it from the integration test project.
/// This pattern is in Microsoft's official integration testing docs and is the universally accepted way to expose the implicit Program class to test projects.
/// The underlying reason is a C# compiler quirk: top-level statements generate an internal Program class, and internal types aren't visible across assembly boundaries. WebApplicationFactory<Program> lives in the test assembly, 
/// so it can't see an internal Program.
///The public partial class Program { } declaration merges with the compiler-generated one and makes it public, which is all WebApplicationFactory needs.
/// /// </summary>
public partial class Program { }